name: Imprimir nombre y expediente

on:
  push:
    branches:
      - main

jobs:
  imprimir:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  

    - name: Nombre
      run: echo "Octavio Valdez"
      
    - name: Node Version
      run: node --version

    - name: Expediente
      run: echo "712153"
